## ver_3.3.4
FROM alpine:latest as builder
MAINTAINER niiv0832 <dockerhubme-ssr@yahoo.com>

ARG SSURL="https://github.com/shadowsocks/shadowsocks-libev"
ARG EDGE="--repository=http://dl-cdn.alpinelinux.org/alpine/edge/main"


RUN \
      apk update && \
      apk upgrade && \
      apk add \
              git \
              autoconf \
              automake \
              libtool \
              linux-headers \
              mbedtls-dev \
              libsodium-dev \
              pcre-dev \
              libev-dev \
              c-ares-dev \
              asciidoc \
              xmlto \
              gcc \
              alpine-sdk && \
      apk add libbloom-dev ${EDGE} && \
      apk add libcork-dev ${EDGE} && \
      apk add libcorkipset-dev ${EDGE} && \
##      
      mkdir /build && \
      cd /buid && \
      git clone https://github.com/shadowsocks/shadowsocks-libev.git && \
      git clone https://github.com/shadowsocks/simple-obfs.git shadowsocks-obfs
##      
      cd /buid/shadowsocks-libev && \
      git submodule update --init --recursive && \
      ./autogen.sh && \     
      ./configure --prefix=/usr --disable-documentation && \
      make && \
##      
      cd /buid/shadowsocks-obfs && \
      git submodule update --init --recursive && \
      ./autogen.sh && \     
      ./configure --prefix=/usr --disable-documentation && \
      make && \

      
